services:
  - type: web
    name: login-sync-api
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: gunicorn login_sync.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: login_sync.settings
      - key: SECRET_KEY
        value: "your-secret-key"
      - key: DATABASE_URL
        value: "your-database-url"
